import type { Catalog, CatalogDocument, Corpus, LibraryLoader } from '../lib/types.js';
const base: CatalogDocument = { id: '2014-04', number: 'FFFS 2014:4', title: 'Hantering av operativa risker', year: 2014, status: 'current', kind: 'fi_consolidated', asOf: '2026-10-09', sourceUrl: 'https://www.fi.se/example/20144/', pdfUrl: 'pdf/2014-04.pdf', amendments: [{ number: 'FFFS 2027:1', effectiveFrom: '2027-01-01', sourceUrl: 'https://www.fi.se/example/amendment/' }], notes: ['Textuttag, läs originalet vid tveksamhet.'], textQuality: 'extracted' };
export const catalog: Catalog = { asOf: '2026-10-09', documents: [base, { ...base, id: '2014-12', number: 'FFFS 2014:12', title: 'Kapitalbuffertar och tillsyn', categories: ['ESG och hållbarhet'], institutions: ['Kreditinstitut'], applicability: {text: 'Kreditinstitut', sourceUrl:'https://www.fi.se/example/'}, tagsEvidence: [{tag:'ESG och hållbarhet',type:'category',evidence:'Hållbarhetsrisker nämns i texten.',sourceUrl:'https://www.fi.se/example/',sectionId:'kap-2-13a',confidence:'editorial'}], kind: 'self_consolidated' }, { ...base, id: '2010-07', number: 'FFFS 2010:7', year: 2010, status: 'repealed' }, { ...base, id: '2027-01', number: 'FFFS 2027:1', year: 2027, status: 'upcoming' }, { ...base, id: '2026-02', number: 'FFFS 2026:2', year: 2026, status: 'repealing' }] };
export const corpus: Corpus = { asOf: catalog.asOf, documents: catalog.documents.map(metadata => ({ id: metadata.id, markdown: `# ${metadata.number}\n\n2 kap.\n\n13 a § Styrelsen ska granska åtgärder för hållbarhetsrisker. Hänvisning till 14 §.\n\n${'Lång text utan bortfall. '.repeat(1400)}`, sections: [
  { id: 'kap-2', title: '2 kap. Styrning', text: '2 kap. Styrning', page: 2 },
  { id: 'kap-2-13a', title: '13 a §', text: 'Styrelsen ska granska åtgärder för hållbarhetsrisker. Hänvisning till 14 §.', page: 3 },
  { id: 'kap-3', title: '3 kap. Annat', text: '3 kap. Annat', page: 4 },
  { id: 'kap-3-13a', title: '13 a §', text: 'En annan bestämmelse.', page: 4 }
] })) };
export const loader: LibraryLoader = { publicBaseUrl: 'https://example.github.io/fffs-bibliotek/', catalog: async () => catalog, corpus: async () => corpus, document: async id => { const doc = corpus.documents.find(doc => doc.id === id); if (!doc) throw new Error('Missing'); return doc; } };
