import fs from 'node:fs/promises';
import path from 'node:path';
import { markdownHtml as mdHtml } from './render-markdown';
import { header, footer, library, documentPage, mcpPage, aboutPage, e, BASE } from '../src/views';
import { euLibraryPage, euDocumentPage } from '../src/eu-views';
import type { EuIndex, EuDocument } from '../lib/eurlex';
import { toolboxPage, actorsPage, evidencePage } from '../src/toolbox-views';
import { SITE_URL, MCP_URL } from '../src/config';
const dist=path.resolve('dist');
const catalog=JSON.parse(await fs.readFile('public/data/catalog.json','utf8'));
const euIndex:EuIndex=JSON.parse(await fs.readFile('public/data/eu/index.json','utf8'));
const template=await fs.readFile(path.join(dist,'index.html'),'utf8');
async function emit(route:string,title:string,body:string,description:string,structured?:any){const url=SITE_URL+route;let html=template.replace(/<title>.*?<\/title>/,`<title>${e(title)} · FFFS-bibliotek</title>`).replace(/<meta name="description"[^>]*\/>/,`<meta name="description" content="${e(description)}" />`).replace('<div id="app"><div class="initial">Läser författningsregistret…</div></div>',`<div id="app">${body}</div>`);html=html.replace('</head>',`<link rel="canonical" href="${e(url)}" />\n<link rel="alternate" type="text/plain" href="${SITE_URL}llms.txt" title="AI access" />\n${structured?`<script type="application/ld+json">${JSON.stringify(structured).replace(/</g,'\\u003c')}</script>`:''}\n</head>`);const filename=path.join(dist,route,'index.html');await fs.mkdir(path.dirname(filename),{recursive:true});await fs.writeFile(filename,html)}
await emit('','Författningar',library(catalog),'Sök och filtrera Finansinspektionens föreskrifter efter institutionstyp, kategori och status. Läs fulltext och hämta Markdown eller PDF.');
await emit('mcp/','MCP och API',mcpPage(),'Publik MCP-server för sökning och hämtning av FFFS. Alla texter och metadata öppet tillgängliga utan inloggning.');
await emit('om/','Om underlaget',aboutPage(catalog),'Källor, daterat urval, dokumenterade rättningar och granskningsbegränsningar i FFFS-biblioteket.');
await emit('verktyg/','Regelverk & compliance',toolboxPage(catalog),'Sök svenska och europeiska regelverk, hitta aktörskällor och samla belägg i ett eget underlag.');
await emit('aktorer/','Aktörskontroll',actorsPage(),'Ingångar till OpenSanctions och IOSCO I-SCAN. Se vad källorna omfattar och vilken åtkomst som finns.');
await emit('underlag/','Mitt underlag',evidencePage(),'Samla källor och egna anteckningar lokalt. Exportera underlaget som Markdown och JSON.');
await emit('eu/','EU-regler',euLibraryPage(euIndex,catalog),'Sök i svenska EU-texter och följ kopplingarna till FFFS. Artiklar, versioner och originalkällor.');
for(const summary of euIndex.documents){
 const d:EuDocument=JSON.parse(await fs.readFile(`public/data/eu/documents/${summary.id}.json`,'utf8'));
 const html=d.sections.map(section=>{
  const blocks=section.markdown.split(/\n\n/);const plain=(value:string)=>value.replace(/\s+/g,' ').trim();
  if(section.kind==='article'&&plain(blocks[0])===`Artikel ${section.number}`){blocks.shift();const subtitle=section.title.split(' — ').slice(1).join(' — ');if(subtitle&&plain(blocks[0])===plain(subtitle))blocks.shift()}
  else if(section.kind!=='preamble'&&plain(blocks[0])===plain(section.title))blocks.shift();
  return `<a id="${e(section.id)}"></a>${section.kind==='article'?`<button class="btn article-save" data-save-eu="${e(d.id)}" data-article="${e(section.id)}">Spara artikel ${e(section.number)} i underlag</button>`:''}<h2>${e(section.title)}</h2>${mdHtml(blocks.join('\n\n'),d)}`;
 }).join('\n');
 await emit(`eu/${d.id}/`,d.label||d.title,euDocumentPage(d,catalog,html),`${d.title}. Svensk lästext med artikelankare och källor. ${d.versionKind==='consolidated'?'Konsoliderad '+d.consolidationDate:'Ursprunglig lydelse'}.`,{'@context':'https://schema.org','@type':'DigitalDocument',name:d.title,identifier:d.id,inLanguage:'sv',url:SITE_URL+`eu/${d.id}/`,dateModified:d.retrievedAt,isBasedOn:d.sourceUrl});
}
for(const d of catalog.documents){const content=JSON.parse(await fs.readFile(`public/data/documents/${d.id}.json`,'utf8'));const jsonld={'@context':'https://schema.org','@type':'DigitalDocument',name:`${d.number}: ${d.title}`,identifier:d.number,inLanguage:'sv',url:d.canonicalUrl??SITE_URL+`fffs/${d.id}/`,dateModified:catalog.asOf,isBasedOn:d.sourceUrl,encoding:[{'@type':'MediaObject',encodingFormat:'text/markdown',contentUrl:SITE_URL+d.markdownUrl},{'@type':'MediaObject',encodingFormat:'application/pdf',contentUrl:SITE_URL+d.pdfUrl}],keywords:[...(d.categories??[]),...(d.institutions??[])]};await emit(`fffs/${d.id}/`,d.number+' – '+d.title,documentPage(catalog,d,content,mdHtml(content.markdown,d),euIndex),`${d.number}: ${d.title}. Fulltext, tillämpningsområde, källor, EU-kopplingar och nedladdningsbar PDF.`,jsonld)}
const routes=['','mcp/','om/','verktyg/','aktorer/','underlag/','eu/',...euIndex.documents.map(d=>`eu/${d.id}/`),...catalog.documents.map((d:any)=>`fffs/${d.id}/`)];await fs.writeFile(path.join(dist,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${routes.map(r=>`<url><loc>${e(SITE_URL+r)}</loc><lastmod>${catalog.asOf}</lastmod></url>`).join('')}</urlset>\n`);
await fs.writeFile(path.join(dist,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${SITE_URL}sitemap.xml\n`);
await fs.writeFile(path.join(dist,'llms.txt'),`# FFFS-bibliotek\n\nOpen read-only library of Swedish Finansinspektionen regulations. Snapshot: ${catalog.asOf}.\n\n## Toolbox\n- Start: ${SITE_URL}verktyg/\n- EU index and coverage: ${SITE_URL}data/eu/index.json\n- EU fulltext corpus: ${SITE_URL}data/eu/search.json\n- EU document JSON: ${SITE_URL}data/eu/documents/{CELEX}.json\n- EU Markdown: ${SITE_URL}eu-documents/{CELEX}.md\n- EU static readers: ${SITE_URL}eu/{CELEX}/\n- Public tools: search_eu, get_eu_document, get_eu_article, get_regulatory_links, get_toolbox_status. Long text is paginated. EU coverage is a linked subset, not all of EUR-Lex. Respect original/consolidated edition and date.\n- OpenSanctions and I-SCAN are external web entrypoints; automatic screening is not enabled. Evidence cases remain local in the user's browser and are not MCP resources.\n\n## Access\n- MCP Streamable HTTP, no API key: ${MCP_URL}\n- Catalog, all metadata/status/tags/EU relations: ${SITE_URL}data/catalog.json\n- Complete corpus, all Markdown and sections: ${SITE_URL}data/search.json\n- Document JSON: ${SITE_URL}data/documents/{id}.json\n- Markdown: ${SITE_URL}documents/{id}.md\n- PDF: ${SITE_URL}pdf/{id}.pdf\n- Static fulltext HTML: ${SITE_URL}fffs/{id}/\n- Sitemap: ${SITE_URL}sitemap.xml\n\nIDs use YYYY-NN, e.g. 2014-04. All 130 documents are accessible. Default searches include current selection; request status=all for upcoming, repealed and repealing acts. get_fffs and get_section paginate long content using nextCursor; continue until null. Do not stop after the first page.\n\n## Provenance and limits\nOriginal source links, amendment history, status, effective dates, applicability evidence and EU relationships travel with metadata. Machine-extracted web texts may contain extraction errors; original PDF matters for tables and formulas. Self-consolidated documents are explicitly labeled. Status is a corrected register-based selection as of the snapshot, not a guarantee of legal completeness. EU relations distinguish implements, supplements and references. No mapped relation is not proof of no EU relationship.\n\n## Documents\n${catalog.documents.map((d:any)=>`- [${d.number}: ${d.title}](${SITE_URL}documents/${d.id}.md) — ${d.status}`).join('\n')}\n`);
await fs.writeFile(path.join(dist,'.nojekyll'),'');
await fs.writeFile(path.join(dist,'404.html'),template.replace('<div id="app"><div class="initial">Läser författningsregistret…</div></div>',`<div id="app">${header()}<main class="info" data-route="404"><h1>Sidan hittades inte</h1><p><a href="${BASE}">Sök i författningsbiblioteket</a></p></main>${footer()}</div>`));
console.log(`Prerendered ${catalog.documents.length} fulltext documents + index, MCP, sources, sitemap, llms.txt.`);
