import { BASE, e } from './views';
import { euResultRow } from './eu-views';
import { searchEuDocuments, type EuIndex, type EuSearchCorpus } from '../lib/eurlex';
export async function startEuLibrary(){
 const json=async(path:string)=>{const r=await fetch(BASE+path);if(!r.ok)throw Error(`EU-filen kunde inte hämtas (${r.status}).`);return r.json()};
 const [index,catalog]:[EuIndex,any]=await Promise.all([json('data/eu/index.json'),json('data/catalog.json')]);
 const params=new URLSearchParams(location.search);const input=document.getElementById('eu-query') as HTMLInputElement;input.value=params.get('q')??'';
 const institution=document.getElementById('eu-institution') as HTMLSelectElement;institution.value=params.get('institution')??'all';if(!institution.value)institution.value='all';
 const version=document.getElementById('eu-version') as HTMLSelectElement;version.value=params.get('version')??'all';if(!version.value)version.value='all';
 const force=document.getElementById('eu-force') as HTMLSelectElement;force.value=params.get('force')??'all';if(!force.value)force.value='all';
 let corpus:Promise<EuSearchCorpus>|undefined;let request=0;let offset=0;let timer:ReturnType<typeof setTimeout>;
 const update=async()=>{const rev=++request;const q=input.value.trim();const query=new URLSearchParams();if(q)query.set('q',q);if(institution.value!=='all')query.set('institution',institution.value);if(version.value!=='all')query.set('version',version.value);if(force.value!=='all')query.set('force',force.value);history.replaceState(null,'',BASE+'eu/'+(query.size?'?'+query:''));
 const results=document.getElementById('eu-results')!;const count=document.getElementById('eu-count')!;
 try{if(q)count.textContent='Söker i EU-texterna…';const data=q?await(corpus??=json('data/eu/search.json').catch(error=>{corpus=undefined;throw error})):index;if(rev!==request)return;const matches=searchEuDocuments(data,q,{limit:100});const byId=new Map(index.documents.map(d=>[d.id,d]));const allowed=new Set(catalog.documents.filter((d:any)=>institution.value==='all'||d.institutions?.includes(institution.value)).map((d:any)=>d.id));const rows=matches.filter(h=>{const d=byId.get(h.id)!;return (institution.value==='all'||d.linkedFffs.some(id=>allowed.has(id)))&&(version.value==='all'||version.value===d.versionKind)&&(force.value==='all'||force.value===(d.inForce===null?'unknown':String(d.inForce)))});count.textContent=`${rows.length} EU-rättsakter${q?' matchar sökningen':''}`;offset=Math.min(offset,Math.max(0,Math.floor((rows.length-1)/20)*20));results.innerHTML=rows.slice(offset,offset+20).map(hit=>euResultRow(byId.get(hit.id)!,q?hit:undefined)).join('')||'<div class="empty"><strong>Inga träffar i det importerade urvalet</strong>Prova färre filter, eller sök i hela EUR-Lex via länken nedan.</div>';const pagination=document.getElementById('eu-pagination')!;pagination.innerHTML=rows.length>20?`<div class="pager"><span>Visar ${offset+1}–${Math.min(offset+20,rows.length)} av ${rows.length}</span><div class="pager-buttons"><button class="btn" id="eu-prev" ${offset===0?'disabled':''}>Föregående</button><button class="btn" id="eu-next" ${offset+20>=rows.length?'disabled':''}>Nästa</button></div></div>`:'';document.getElementById('eu-prev')?.addEventListener('click',()=>{offset-=20;update();input.scrollIntoView({block:'center'})});document.getElementById('eu-next')?.addEventListener('click',()=>{offset+=20;update();input.scrollIntoView({block:'center'})})}catch(cause){if(rev===request){count.textContent='Sökningen kunde inte slutföras';results.innerHTML=`<div class="error">${e(cause instanceof Error?cause.message:cause)}</div>`}}};
 input.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>{offset=0;update()},200)});for(const control of [institution,version,force])control.addEventListener('change',()=>{offset=0;update()});await update();
}
