import { BASE, e, header, footer, docUrl, shortTitle } from './views';

export function toolboxPage(catalog:any) {
  return `${header('toolbox')}<main class="toolbox" id="main" data-route="toolbox">
  <div class="toolbox-intro"><p class="eyebrow">Regelverk & compliance</p><h1>Från fråga till källa.</h1><p>Sök svenska föreskrifter och EU-regler. Följ sambanden, läs bestämmelserna och samla det du behöver i ett underlag.</p></div>
  <form id="global-search" class="global-search"><label class="sr-only" for="global-query">Sök i FFFS och EU-regler</label><input id="global-query" type="search" placeholder="Sök ett ämne, FFFS-nummer eller CELEX…" required maxlength="240"><button class="btn primary">Sök regelverk</button></form>
  <div id="global-results" aria-live="polite"></div>
  <div class="workflows"><a class="workflow-card" href="${BASE}"><span class="workflow-number">01 / Svenska regler</span><h2>Hitta rätt FFFS</h2><p>Välj institutionstyp, filtrera författningar och läs med original och PDF nära till hands.</p><span>${catalog.documents.length} författningsakter <b aria-hidden="true">↗</b></span></a><a class="workflow-card" href="${BASE}eu/"><span class="workflow-number">02 / Europeiska regler</span><h2>Följ EU-kopplingen</h2><p>Läs EU-rättsakter och enskilda artiklar. Se vilka svenska föreskrifter som hänvisar till dem.</p><span>EUR-Lex & FFFS <b aria-hidden="true">↗</b></span></a><a class="workflow-card" href="${BASE}aktorer/"><span class="workflow-number">03 / Aktörskontroll</span><h2>Kontrollera en aktör</h2><p>Hitta sanktions- och PEP-information hos OpenSanctions och tillsynsvarningar hos IOSCO I-SCAN.</p><span>Källor & åtkomst <b aria-hidden="true">↗</b></span></a><a class="workflow-card" href="${BASE}underlag/"><span class="workflow-number">04 / Ditt underlag</span><h2>Samla beläggen</h2><p>Spara bestämmelser, skriv anteckningar och exportera källor och versioner som Markdown eller JSON.</p><span>Sparas i din webbläsare <b aria-hidden="true">↗</b></span></a></div>
  <section class="journey"><div><p class="eyebrow">Börja med en konkret fråga</p><h2>Digital motståndskraft för kreditinstitut</h2><p>Hitta de svenska reglerna, följ kopplingen till DORA och spara relevanta artiklar i ditt underlag.</p></div><a class="btn" href="${BASE}?institution=Kreditinstitut&q=DORA">Visa FFFS om DORA →</a></section>
  <div class="toolbox-footnote"><p><strong>Källorna följer med.</strong> Varje lästext visar källa, utgåva och hämtningstid. Sparade belägg och egna anteckningar hålls isär.</p><a href="${BASE}mcp/">Samma material via publik MCP →</a></div></main>${footer()}`;
}

export function actorsPage(){return `${header('actors')}<main class="toolbox" id="main" data-route="actors"><div class="toolbox-intro"><p class="eyebrow">Aktörskontroll</p><h1>Rätt källa för rätt kontroll.</h1><p>Sanktioner, politiskt utsatta personer och tillsynsvarningar har olika betydelse. Här hittar du källorna och ser vilken åtkomst som finns.</p></div><div class="provider-grid"><section class="provider-card"><span class="status-badge">Öppen webbplats · API kräver nyckel</span><h2>OpenSanctions</h2><p>Sök personer och organisationer i källor om sanktioner, politisk exponering och andra riskindikatorer.</p><form id="provider-search"><label for="actor-name">Person eller organisation</label><input id="actor-name" name="name" maxlength="200" type="search" placeholder="Ange namn" required><button class="btn primary">Sök på OpenSanctions ↗</button></form><p class="subtle">Sökningen öppnar leverantörens webbplats i en ny flik. Ingen automatisk API-kontroll utförs här.</p><details><summary>Om API och matchning</summary><p>Automatisk screening kräver egen OpenSanctions-åtkomst. En namnträff är en kandidat som måste bedömas mot identifierare och källbelägg. Den är inte en bekräftad identitet eller ett beslut.</p><a href="https://www.opensanctions.org/docs/api/">Officiell API-dokumentation</a></details></section><section class="provider-card"><span class="status-badge">Officiell portal</span><h2>IOSCO I-SCAN</h2><p>Varningar från tillsynsmyndigheter om misstänkta eller olicensierade finansiella aktörer.</p><a class="btn primary" href="https://www.iosco.org/i-scan/" target="_blank" rel="noopener noreferrer">Öppna I-SCAN ↗</a><p class="subtle">Varningar visas i IOSCO:s portal. Ingen varningskontroll har utförts av denna sida.</p><details><summary>Om varningar och åtkomst</summary><p>En I-SCAN-varning är inte en sanktionslistning. Läs utfärdande myndighet, datum, berörd aktör och den ursprungliga varningen. IOSCO:s API kräver ett undertecknat användningsavtal och åtkomstuppgifter. Denna utgåva använder den öppna webbportalen.</p><a href="https://www.iosco.org/i-scan/IOSCO_I-SCAN_API_Terms_of_Use_Agreement.pdf">API-villkor hos IOSCO</a></details></section></div><section class="journey"><div><h2>Ta med det du hittar</h2><p>Öppna originalkällan och spara dess länk och ett eget utdrag i underlaget. Ange vad du har kontrollerat och vad som återstår.</p></div><a class="btn" href="${BASE}underlag/">Lägg till källbelägg →</a></section></main>${footer()}`}

export function evidencePage(){return `${header('evidence')}<main class="toolbox" id="main" data-route="evidence"><div class="toolbox-intro"><p class="eyebrow">Ditt underlag</p><h1>Källor, anteckningar och bedömningar.</h1><p>Samla belägg när du läser och exportera dem när du är klar. Underlaget sparas lokalt i den här webbläsaren. Exportera en fil om du vill behålla en kopia.</p></div><div id="evidence-error" role="alert"></div><div class="case-toolbar"><label for="case-title">Underlagets namn<input id="case-title" maxlength="200" placeholder="Nytt underlag"></label><button class="btn" id="save-case-title">Spara namn</button><div class="actions"><button class="btn" id="export-md">Exportera Markdown</button><button class="btn" id="export-json">Exportera JSON</button><label class="btn import-button">Importera JSON<input id="import-case" type="file" accept="application/json,.json" class="sr-only"></label></div></div><p class="subtle" id="evidence-count" aria-live="polite"></p><div id="evidence-records"></div><details class="manual-evidence"><summary>Lägg till en extern källa</summary><form id="manual-evidence"><div class="field-pair"><label>Rubrik<input name="title" required maxlength="300"></label><label>Källans HTTPS-länk<input name="url" required type="url" placeholder="https://…" maxlength="2000"></label></div><label>Utdrag ur källan<textarea name="excerpt" rows="3" maxlength="8000"></textarea></label><label>Din anteckning<textarea name="note" rows="2" maxlength="4000"></textarea></label><button class="btn primary">Spara källan lokalt</button></form></details><p class="library-note">Underlaget är dina valda belägg och egna bedömningar. Det är ingen automatiskt genomförd compliancekontroll. Uppgifterna skickas inte till en ärendeserver.</p></main>${footer()}`}

export function relatedFffs(catalog:any,celex:string){return catalog.documents.filter((d:any)=>(d.euRelations??[]).some((r:any)=>r.celex===celex||r.url?.includes(celex)))}
export function relatedFffsHtml(catalog:any,celex:string){const docs=relatedFffs(catalog,celex);return docs.length?`<section class="eu-section"><details class="eu-group"><summary>Svenska föreskrifter med kopplingar (${docs.length})</summary><p class="subtle">Kopplingar i bibliotekets källor. Institutionstaggar är sökhjälp, inte en fullständig EU-tillämpningsbedömning.</p>${docs.map((d:any)=>`<a class="eu-related" href="${docUrl(d.id)}"><strong>${e(d.number)}</strong> ${e(shortTitle(d.title))}<small>${e(d.institutions?.join(' · '))}</small></a>`).join('')}</details></section>`:''}
